#!/bin/bash

JOBNAME=$1
MAXJOBS=$2

function nr () { qstat | grep mpx017 | grep -c " r " ; }
function nq () { qstat | grep " qw " | awk 'BEGIN{s=0;}{a=gensub("-.*$","","g",$9); b=gensub(":.*$","","g",gensub("^.*-","","g",$9)); s+=(1+b-a);}END{print s}' ; }


while true; do

  NRUN=`nr`
  NQUE=`nq`  
  NJOBS=`expr $NRUN + $NQUE`;
  echo ${NRUN} jobs running, ${NQUE} jobs queued, total ${NJOBS}
  if [ "${NJOBS}" -lt "${MAXJOBS}" ]; then

      echo Only ${NJOBS} jobs running/queued...
      echo ...tidying up running.\* files...
      ./tidyall > /dev/null
      ./tidyout > /dev/null
      echo ...queuing more jobs...

      while [ "${NJOBS}" -lt "${MAXJOBS}" ]; do
      echo Only ${NJOBS} jobs running/queued...
       echo submitting ${JOBNAME} to queue 
       qsub ${JOBNAME};
       sleep 5;
       NRUN=`nr`
       NQUE=`nq`  
       NJOBS=`expr $NRUN + $NQUE`;
      done;
      qstat
  fi;
  date
  sleep 3600
done;
